# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports adr_in[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports adr_in[0]]
set_property PACKAGE_PIN V16 [get_ports adr_in[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports adr_in[1]]
set_property PACKAGE_PIN W16 [get_ports adr_in[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports adr_in[2]]
set_property PACKAGE_PIN W17 [get_ports adr_in[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports adr_in[3]]

set_property PACKAGE_PIN V2 [get_ports data_in[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports data_in[0]]
set_property PACKAGE_PIN T3 [get_ports data_in[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports data_in[1]]
set_property PACKAGE_PIN T2 [get_ports data_in[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports data_in[2]]
set_property PACKAGE_PIN R3 [get_ports data_in[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports data_in[3]]
set_property PACKAGE_PIN W2 [get_ports data_in[4]]					
	set_property IOSTANDARD LVCMOS33 [get_ports data_in[4]]
set_property PACKAGE_PIN U1 [get_ports data_in[5]]					
	set_property IOSTANDARD LVCMOS33 [get_ports data_in[5]]
set_property PACKAGE_PIN T1 [get_ports data_in[6]]					
	set_property IOSTANDARD LVCMOS33 [get_ports data_in[6]]
set_property PACKAGE_PIN R2 [get_ports data_in[7]]					
	set_property IOSTANDARD LVCMOS33 [get_ports data_in[7]]
 

# LEDs
set_property PACKAGE_PIN U16 [get_ports adrled[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports adrled[0]]
set_property PACKAGE_PIN E19 [get_ports adrled[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports adrled[1]]
set_property PACKAGE_PIN U19 [get_ports adrled[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports adrled[2]]
set_property PACKAGE_PIN V19 [get_ports adrled[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports adrled[3]]

set_property PACKAGE_PIN V13 [get_ports dataled[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports dataled[0]]
set_property PACKAGE_PIN V3 [get_ports dataled[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports dataled[1]]
set_property PACKAGE_PIN W3 [get_ports dataled[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports dataled[2]]
set_property PACKAGE_PIN U3 [get_ports dataled[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports dataled[3]]
set_property PACKAGE_PIN P3 [get_ports dataled[4]]					
	set_property IOSTANDARD LVCMOS33 [get_ports dataled[4]]
set_property PACKAGE_PIN N3 [get_ports dataled[5]]					
	set_property IOSTANDARD LVCMOS33 [get_ports dataled[5]]
set_property PACKAGE_PIN P1 [get_ports dataled[6]]					
	set_property IOSTANDARD LVCMOS33 [get_ports dataled[6]]
set_property PACKAGE_PIN L1 [get_ports dataled[7]]					
	set_property IOSTANDARD LVCMOS33 [get_ports dataled[7]]
	
	
#7 segment display
set_property PACKAGE_PIN W7 [get_ports thesegment[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports thesegment[0]]
set_property PACKAGE_PIN W6 [get_ports thesegment[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports thesegment[1]]
set_property PACKAGE_PIN U8 [get_ports thesegment[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports thesegment[2]]
set_property PACKAGE_PIN V8 [get_ports thesegment[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports thesegment[3]]
set_property PACKAGE_PIN U5 [get_ports thesegment[4]]					
	set_property IOSTANDARD LVCMOS33 [get_ports thesegment[4]]
set_property PACKAGE_PIN V5 [get_ports thesegment[5]]					
	set_property IOSTANDARD LVCMOS33 [get_ports thesegment[5]]
set_property PACKAGE_PIN U7 [get_ports thesegment[6]]					
	set_property IOSTANDARD LVCMOS33 [get_ports thesegment[6]]
set_property PACKAGE_PIN W14 [get_ports reset]					
	set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN V7 [get_ports thesegment[7]]							
	set_property IOSTANDARD LVCMOS33 [get_ports thesegment[7]]

set_property PACKAGE_PIN U2 [get_ports {theenable[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {theenable[3]}]
set_property PACKAGE_PIN U4 [get_ports {theenable[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {theenable[2]}]
set_property PACKAGE_PIN V4 [get_ports {theenable[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {theenable[1]}]
set_property PACKAGE_PIN W4 [get_ports {theenable[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {theenable[0]}]


##Buttons
set_property PACKAGE_PIN U18 [get_ports addInput]						
	set_property IOSTANDARD LVCMOS33 [get_ports addInput]
set_property PACKAGE_PIN T18 [get_ports checkSum]						
	set_property IOSTANDARD LVCMOS33 [get_ports checkSum]
set_property PACKAGE_PIN W19 [get_ports displayP]						
	set_property IOSTANDARD LVCMOS33 [get_ports displayP]
set_property PACKAGE_PIN T17 [get_ports displayN]						
	set_property IOSTANDARD LVCMOS33 [get_ports displayN]
set_property PACKAGE_PIN U17 [get_ports displayC]						
	set_property IOSTANDARD LVCMOS33 [get_ports displayC]
 

